In [1]:
# Importação das bibliotecas
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import make_column_transformer

In [2]:
dataset = pd.read_csv("soybean.csv")
dataset

date plant-stand   precip     temp hail         crop-hist  \
0    october      normal  gt-norm     norm  yes       same-lst-yr   
1     august      normal  gt-norm     norm  yes  same-lst-two-yrs   
2       july      normal  gt-norm     norm  yes       same-lst-yr   
3       july      normal  gt-norm     norm  yes       same-lst-yr   
4    october      normal  gt-norm     norm  yes  same-lst-two-yrs   
..       ...         ...      ...      ...  ...               ...   
678    april           ?        ?        ?    ?                 ?   
679    april   lt-normal        ?  lt-norm    ?     diff-lst-year   
680     june   lt-normal        ?  lt-norm    ?     diff-lst-year   
681    april   lt-normal        ?  lt-norm    ?       same-lst-yr   
682     june   lt-normal        ?  lt-norm    ?       same-lst-yr   

    area-damaged    severity   seed-tmt germination  ... sclerotia fruit-pods  \
0      low-areas  pot-severe       none      90-100  ...    absent       norm   
1      scattered      severe  fungicide       80-89  ...    absent       norm   
2      scattered      severe  fungicide       lt-80  ...    absent       norm   
3      scattered      severe       none       80-89  ...    absent       norm   
4      scattered  pot-severe       none       lt-80  ...    absent       norm   
..           ...         ...        ...         ...  ...       ...        ...   
678  upper-areas           ?          ?           ?  ...         ?          ?   
679    scattered           ?          ?           ?  ...         ?        dna   
680    scattered           ?          ?           ?  ...         ?        dna   
681  whole-field           ?          ?           ?  ...         ?        dna   
682  whole-field           ?          ?           ?  ...         ?        dna   

    fruit-spots  seed mold-growth seed-discolor seed-size shriveling   roots  \
0           dna  norm      absent        absent      norm     absent    norm   
1           dna  norm      absent        absent      norm     absent    norm   
2           dna  norm      absent        absent      norm     absent    norm   
3           dna  norm      absent        absent      norm     absent    norm   
4           dna  norm      absent        absent      norm     absent    norm   
..          ...   ...         ...           ...       ...        ...     ...   
678           ?     ?           ?             ?         ?          ?       ?   
679           ?     ?           ?             ?         ?          ?  rotted   
680           ?     ?           ?             ?         ?          ?  rotted   
681           ?     ?           ?             ?         ?          ?  rotted   
682           ?     ?           ?             ?         ?          ?  rotted   

                     class  
0    diaporthe-stem-canker  
1    diaporthe-stem-canker  
2    diaporthe-stem-canker  
3    diaporthe-stem-canker  
4    diaporthe-stem-canker  
..                     ...  
678           2-4-d-injury  
679       herbicide-injury  
680       herbicide-injury  
681       herbicide-injury  
682       herbicide-injury  

[683 rows x 36 columns]

In [3]:
#separação dos variáveis, ignoro primeira pois não tem valor semântico
X = dataset.iloc[:,0:35].values
y = dataset.iloc[:, 35].values
#temos um arry e não mais um data frame
X[0:2]

array([['october', 'normal', 'gt-norm', 'norm', 'yes', 'same-lst-yr',
        'low-areas', 'pot-severe', 'none', '90-100', 'abnorm', 'abnorm',
        'absent', 'dna', 'dna', 'absent', 'absent', 'absent', 'abnorm',
        'no', 'above-sec-nde', 'brown', 'present', 'firm-and-dry',
        'absent', 'none', 'absent', 'norm', 'dna', 'norm', 'absent',
        'absent', 'norm', 'absent', 'norm'],
       ['august', 'normal', 'gt-norm', 'norm', 'yes', 'same-lst-two-yrs',
        'scattered', 'severe', 'fungicide', '80-89', 'abnorm', 'abnorm',
        'absent', 'dna', 'dna', 'absent', 'absent', 'absent', 'abnorm',
        'yes', 'above-sec-nde', 'brown', 'present', 'firm-and-dry',
        'absent', 'none', 'absent', 'norm', 'dna', 'norm', 'absent',
        'absent', 'norm', 'absent', 'norm']], dtype=object)

In [4]:
labelencoder = LabelEncoder()

for x in range(35):
    X[:, x] = labelencoder.fit_transform(X[:, x])

X = X.astype('float')
X[0]

array([6., 2., 1., 3., 2., 4., 1., 2., 2., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 2., 2., 1., 3., 1., 4., 4., 2., 1., 1., 2., 1.,
       2.])

In [5]:
#Laber encoder com a classe
labelencoder_Y = LabelEncoder()
y = labelencoder_Y.fit_transform(y)
classe_dummy = np_utils.to_categorical(y)
classe_dummy

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [6]:
#separação em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, classe_dummy, test_size = 0.2, random_state = 0)
print(len(X_train),len(X_test),len(y_train),len(y_test))

546 137 546 137


In [7]:
y_test.shape

(137, 19)

In [8]:
X_test.shape

(137, 35)

In [9]:
classifier = Sequential()
classifier.add(Dense(units = 18, input_dim = 35))
classifier.add(Dense(units = 38))
classifier.add(Dense(units = 19, activation = 'softmax'))
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 18)                648       
                                                                 
 dense_1 (Dense)             (None, 38)                722       
                                                                 
 dense_2 (Dense)             (None, 19)                741       
                                                                 
Total params: 2,111
Trainable params: 2,111
Non-trainable params: 0
_________________________________________________________________


In [10]:
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, epochs = 100, validation_data = (X_test, y_test))

Epoch 1/100
18/18 [==============================] - 1s 9ms/step - loss: 3.4637 - accuracy: 0.1062 - val_loss: 2.7515 - val_accuracy: 0.2044
Epoch 2/100
18/18 [==============================] - 0s 2ms/step - loss: 2.5678 - accuracy: 0.2637 - val_loss: 2.4543 - val_accuracy: 0.2555
Epoch 3/100
18/18 [==============================] - 0s 2ms/step - loss: 2.2847 - accuracy: 0.3516 - val_loss: 2.2316 - val_accuracy: 0.3285
Epoch 4/100
18/18 [==============================] - 0s 2ms/step - loss: 2.0758 - accuracy: 0.4066 - val_loss: 2.0680 - val_accuracy: 0.3650
Epoch 5/100
18/18 [==============================] - 0s 2ms/step - loss: 1.9276 - accuracy: 0.4487 - val_loss: 1.9312 - val_accuracy: 0.4380
Epoch 6/100
18/18 [==============================] - 0s 2ms/step - loss: 1.7781 - accuracy: 0.4963 - val_loss: 1.8209 - val_accuracy: 0.4818
Epoch 7/100
18/18 [==============================] - 0s 2ms/step - loss: 1.6617 - accuracy: 0.5403 - val_loss: 1.7172 - val_accuracy: 0.4964
Epoch 8/100
1

Epoch 59/100
18/18 [==============================] - 0s 2ms/step - loss: 0.3319 - accuracy: 0.8846 - val_loss: 0.4169 - val_accuracy: 0.8905
Epoch 60/100
18/18 [==============================] - 0s 2ms/step - loss: 0.3201 - accuracy: 0.9048 - val_loss: 0.3979 - val_accuracy: 0.8832
Epoch 61/100
18/18 [==============================] - 0s 2ms/step - loss: 0.3193 - accuracy: 0.8846 - val_loss: 0.4157 - val_accuracy: 0.8613
Epoch 62/100
18/18 [==============================] - 0s 2ms/step - loss: 0.3376 - accuracy: 0.8956 - val_loss: 0.3936 - val_accuracy: 0.8832
Epoch 63/100
18/18 [==============================] - 0s 2ms/step - loss: 0.3479 - accuracy: 0.8810 - val_loss: 0.4220 - val_accuracy: 0.8686
Epoch 64/100
18/18 [==============================] - 0s 2ms/step - loss: 0.3246 - accuracy: 0.8956 - val_loss: 0.3808 - val_accuracy: 0.8905
Epoch 65/100
18/18 [==============================] - 0s 2ms/step - loss: 0.3018 - accuracy: 0.8956 - val_loss: 0.3772 - val_accuracy: 0.8905
Epoch 

In [11]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred[0:2]

5/5 [==============================] - 0s 750us/step


array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False, False,
        False]])

In [12]:
y_teste_matrix = [np.argmax(t) for t in y_test]
y_previsao_matrix = [np.argmax(t) for t in y_pred]

In [13]:
taxa_acerto = accuracy_score(y_teste_matrix, y_previsao_matrix)
taxa_acerto

0.8759124087591241